### ISSUE TITLE
BouncyCastle >= v1.63 breaks OCSP lookup

### ISSUE THREAD

**Issue by runeflobakk** [digipost/certificate-validator#15]
BouncyCastle from version 1.63 will throw `ClassCastException` here:
https://github.com/digipost/certificate-validator/blob/master/src/main/java/no/digipost/security/ocsp/OcspUtils.java#L71

```
java.lang.ClassCastException: class org.bouncycastle.asn1.DLTaggedObject cannot be cast to class org.bouncycastle.asn1.DERTaggedObject
```

**Comment by runeflobakk** [comment]
If you wanna have a crack at it, @oyvindn. Or hack. Or phr3ak. Or zinga-ling-zackity-schmack at it.

**Comment by runeflobakk** [comment]
![hacktheplanet](https://user-images.githubusercontent.com/174823/66896079-7e356d00-eff4-11e9-86a9-0c8dac689601.gif)

**Comment by oyvindn** [comment]
https://github.com/digipost/certificate-validator/pull/16
